const DESKTOP_DISPLAY_LIMIT = 4
const TABLET_DISPLAY_LIMIT = 2
const MOBILE_DISPLAY_LIMIT = 2

const MAX_MOVIES_DURATION = 40

const EMAIL_PATTERN = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"

const USERNAME_PATTERN = "^[A-Za-zА-Яа-яЁё /s -]+$"

export {
  DESKTOP_DISPLAY_LIMIT,
  TABLET_DISPLAY_LIMIT,
  MOBILE_DISPLAY_LIMIT,
  MAX_MOVIES_DURATION,
  EMAIL_PATTERN,
  USERNAME_PATTERN,
}
